In [ ]:
#webcam
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        cv2.imshow("frame", frame)
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()


In [1]:
Violet=(148, 0, 211)
Indigo=(75, 0, 130)
Blue=(0, 0, 255)
Green=(0, 255, 0)
Yellow=(255, 255, 0)
Orange=(255, 127, 0)
Red=(255, 0 , 0)

In [10]:
#just show video from sequence
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\GitClone\\1_camera_gait_analysis\walking_77_image_sequence\\img (%d).jpg")

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        cv2.imshow("image", frame)
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()

In [5]:
#just show video
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\GitClone\\1_camera_gait_analysis\walking_videos\\DSC_0077.MOV")

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        cv2.imshow("image", frame)
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()

In [6]:
#MOG
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\GitClone\\1_camera_gait_analysis\walking_videos\\DSC_0077.MOV")
fgbg = cv2.bgsegm.createBackgroundSubtractorMOG()

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        fgmask = fgbg.apply(frame)
        cv2.imshow('image',fgmask)
        key = cv2.waitKey(30) 
        if key == 27:
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

In [7]:
#MOG2
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\GitClone\\1_camera_gait_analysis\walking_videos\\DSC_0077.MOV")

subtractor = cv2.createBackgroundSubtractorMOG2(history=1000000, varThreshold=5, detectShadows=False)
        
while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        mask = subtractor.apply(frame)
        cv2.imshow("image", mask)
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()

In [8]:
#Manual
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\GitClone\\1_camera_gait_analysis\walking_videos\\DSC_0077.MOV")
_, first_frame = cap.read()
first_gray = cv2.cvtColor(first_frame, cv2.COLOR_BGR2GRAY)
first_gray = cv2.GaussianBlur(first_gray, (5, 5), 0)
while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        gray_frame = cv2.GaussianBlur(gray_frame, (5, 5), 0)
        difference = cv2.absdiff(first_gray, gray_frame)
        _, difference = cv2.threshold(difference, 25, 255, cv2.THRESH_BINARY)
        cv2.imshow("image", first_frame)
        cv2.imshow("image", frame)
        cv2.imshow("image", difference)
   
        key = cv2.waitKey(30)
        if key == 27:
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

In [9]:
#cornor detection normal image
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\GitClone\\1_camera_gait_analysis\walking_videos\\DSC_0077.MOV")


while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        gray = np.float32(gray)
        dst = cv2.cornerHarris(gray,2,3,0.04)
        #result is dilated for marking the corners, not important
        dst = cv2.dilate(dst,None)
        # Threshold for an optimal value, it may vary depending on the image.
        frame[dst>0.01*dst.max()]=[0,0,255]
        cv2.imshow("image", frame)
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()

In [36]:
#webcam detect marker(with highlight level threshold)
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(cap.isOpened()):
    ret, frame, = cap.read()
    if ret:
        imgray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        imblur1 = cv2.medianBlur(imgray,5)
        imblur2 = cv2.GaussianBlur(imblur1,(5,5),0)
        
        ret,thresh = cv2.threshold(imblur2,250,255,cv2.THRESH_BINARY)

        contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

        #print("Number of objects found = ", len(contours))
       
        
        cv2.drawContours(frame, contours, -1, (0,0,255), 10)
        cv2.imshow("frame", frame)
        
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()

In [13]:
#image edge detection
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
#cv2.resizeWindow('image', 2000,1242)
cv2.resizeWindow('image', 560,996)

img = cv2.imread('C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\GitClone\\1_camera_gait_analysis\Azmall_image\BAzmall.jpg',1)
#img = cv2.imread('fap.png',1)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
blur = cv2.GaussianBlur(gray,(7,7),0)

canny2 = cv2.Canny(blur, 50, 100)
cv2.imshow("image", canny2)
 

k = cv2.waitKey(0)
if k == 27:         # wait for ESC key to exit
    cv2.destroyAllWindows()

In [12]:
#show marker coordinate in image
import cv2
import numpy as np
from matplotlib import pyplot as plt

        
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 560,996)
cv2.namedWindow('image2',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image2', 560,996)

img = cv2.imread('C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\GitClone\\1_camera_gait_analysis\Azmall_image\FAzmall.jpg')
imgray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imblur1 = cv2.medianBlur(imgray,5)
imblur2 = cv2.GaussianBlur(imblur1,(5,5),0)

ret,thresh = cv2.threshold(imblur2,250,255,cv2.THRESH_BINARY)

contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

print("Number of objects found = ", len(contours))

i = 0
for c in contours:
    # calculate moments for each contour
    M = cv2.moments(c)

    # calculate x,y coordinate of center
    if M["m00"] != 0:
        cX = int(M["m10"] / M["m00"])
        cY = int(M["m01"] / M["m00"])
    else:
        cX = 0
        cY = 0

    i+=1
   # print('\nX',i,' ',cX)
    #print('Y',i,' ',cY)
    centroid = "X"+str(i)+":"+str(cX)+", Y"+str(i)+":"+str(cY)
    cv2.putText(img,centroid , (cX - 25, cY - 25),cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255, 255), 2)

cv2.drawContours(img, contours, -1, (0,0,255), 10)
cv2.imshow("image", img)
cv2.imshow("image2",thresh)


 

k = cv2.waitKey(0)
if k == 27:         # wait for ESC key to exit
    cv2.destroyAllWindows()

Number of objects found =  12


In [11]:
#save video

import cv2
import numpy as np
from matplotlib import pyplot as plt
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)
cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\GitClone\\1_camera_gait_analysis\walking_77_image_sequence\\img (%d).jpg")

# Define the codec and create VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('77marked.avi',fourcc, 23.9, (1920,1080))

while(cap.isOpened()):
    ret, frame, = cap.read()
    if ret:
        
        #frame = cv2.flip(frame,0)

        # write the flipped frame
        out.write(frame)
        cv2.imshow("image", frame)
        
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()


In [2]:
import cv2
cv2.destroyAllWindows()

In [44]:
#calibrate camera
import numpy as np
import cv2
import glob

# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((7*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:7].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = cv2.VideoCapture(0)

while(images.isOpened()):
    ret, frame = images.read()
    if ret:
        gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        
        # Find the chess board corners
        ret, corners = cv2.findChessboardCorners(gray, (7,7),None)
        
         # If found, add object points, image points (after refining them)
        if ret == True:
            objpoints.append(objp)

            cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
            imgpoints.append(corners)

            # Draw and display the corners
            cv2.drawChessboardCorners(frame, (7,7), corners,ret)
            ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)
        cv2.imshow('frame',frame)    
        key = cv2.waitKey(100)
        if key == 27:
            break
        
    else: 
        break
images.release()
cv2.destroyAllWindows()

np.savez("B.npz", mtx = mtx, dist = dist , rvecs = rvecs, tvecs = tvecs)

In [49]:
#B.npz checker
data = np.load("B.npz")

a1 = data['mtx']
print(a1)
b1 = data['dist']
print(b1)
a2 = data['rvecs']
print(a2)
b2 = data['tvecs']
print(b2)
print("==========================================")

print(mtx)
print(dist)
print(rvecs)
print(tvecs)



[[584.31172018   0.         314.65223298]
 [  0.         585.78021719 223.07917413]
 [  0.           0.           1.        ]]
[[ 0.05873021  0.0606359  -0.0044461  -0.00275274 -1.22945484]]
[[[-7.68295735e-01]
  [-2.48378520e-01]
  [ 2.61988867e+00]]

 [[-1.65556040e-01]
  [-3.98953077e-01]
  [ 1.30160545e+00]]

 [[-2.28964057e-01]
  [-6.63950031e-01]
  [ 2.90065633e+00]]

 [[-1.59657028e-01]
  [-7.88398276e-01]
  [ 2.89529642e+00]]

 [[-1.80319383e-01]
  [-6.70450588e-01]
  [ 2.96343579e+00]]

 [[ 3.07481236e-03]
  [-2.74907313e-01]
  [ 3.00353306e+00]]

 [[ 8.17823720e-02]
  [-1.69397081e-01]
  [ 1.47457022e+00]]

 [[ 9.26047542e-02]
  [-1.63514634e-01]
  [ 1.49514484e+00]]

 [[-4.40066677e-02]
  [-2.75606645e-01]
  [ 3.03529044e+00]]

 [[ 1.34362038e-01]
  [-1.76229542e-01]
  [ 1.46467755e+00]]

 [[ 1.26655781e-01]
  [-1.02959572e-01]
  [ 1.46931734e+00]]

 [[ 1.41551496e-01]
  [-2.43661062e-01]
  [ 3.06767014e+00]]

 [[ 7.78212323e-02]
  [-2.13013691e-01]
  [ 3.06599734e+00]]

 [[

In [10]:
#draw 3d on chessboard
import cv2
import numpy as np
import glob

# Load previously saved data
with np.load('B.npz') as X:
    mtx, dist, _, _ = [X[i] for i in ('mtx','dist','rvecs','tvecs')]
    
def draw(img, corners, imgpts):
    corner = tuple(corners[0].ravel())
    img = cv2.line(img, corner, tuple(imgpts[0].ravel()), (255,0,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[1].ravel()), (0,255,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[2].ravel()), (0,0,255), 5)
    return img

def drawBox(img, corners, imgpts):
    imgpts = np.int32(imgpts).reshape(-1,2)

    # draw ground floor in green
    img = cv2.drawContours(img, [imgpts[:4]],-1,(0,255,0),-3)

    # draw pillars in blue color
    for i,j in zip(range(4),range(4,8)):
        img = cv2.line(img, tuple(imgpts[i]), tuple(imgpts[j]),(255),3)

    # draw top layer in red color
    img = cv2.drawContours(img, [imgpts[4:]],-1,(0,0,255),3)

    return img


criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
objp = np.zeros((7*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:7].T.reshape(-1,2)

axis = np.float32([[3,0,0], [0,3,0], [0,0,-3]]).reshape(-1,3)

#axis = np.float32([[0,0,0], [0,3,0], [3,3,0], [3,0,0],
#                   [0,0,-3],[0,3,-3],[3,3,-3],[3,0,-3] ])



cap = cv2.VideoCapture(0)

while(cap.isOpened()):
    ret, img = cap.read()
    if ret:
        gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        ret, corners = cv2.findChessboardCorners(gray, (7,7),None,cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_NORMALIZE_IMAGE + cv2.CALIB_CB_FAST_CHECK)

        if ret == True:
            corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
            # Find the rotation and translation vectors.
            _, rvecs, tvecs, inliers  = cv2.solvePnPRansac(objp, corners2, mtx, dist)

            # project 3D points to image plane
            imgpts, jac = cv2.projectPoints(axis, rvecs, tvecs, mtx, dist)

            img = draw(img,corners2,imgpts)
            
        cv2.imshow('img',img)
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()