In [3]:
from keras.models import Sequential

model = Sequential()

In [4]:
from keras.layers import Dense

model.add(Dense(units=64, activation='relu', input_dim=100))
model.add(Dense(units=10, activation='softmax'))

W0723 15:54:48.229483 10396 deprecation_wrapper.py:119] From C:\Users\sunny.DESKTOP-QGFGEEK\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0723 15:54:48.260406 10396 deprecation_wrapper.py:119] From C:\Users\sunny.DESKTOP-QGFGEEK\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [5]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

W0723 15:55:11.368244 10396 deprecation_wrapper.py:119] From C:\Users\sunny.DESKTOP-QGFGEEK\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0723 15:55:11.393211 10396 deprecation_wrapper.py:119] From C:\Users\sunny.DESKTOP-QGFGEEK\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

# Generate dummy data
import numpy as np
x_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
x_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)



Using TensorFlow backend.


In [14]:
print(x_train)

[[0.74166691 0.70987158 0.78570384 ... 0.80473515 0.98504668 0.2750797 ]
 [0.89076776 0.26707435 0.38701443 ... 0.4604779  0.81752711 0.99405299]
 [0.87623624 0.15981996 0.31366024 ... 0.62348022 0.63639584 0.47429301]
 ...
 [0.43334804 0.75619214 0.42524293 ... 0.52037165 0.29683875 0.93832215]
 [0.00848367 0.42552524 0.35193385 ... 0.84323673 0.9563285  0.68324048]
 [0.13258425 0.1306022  0.86685157 ... 0.66103012 0.92169474 0.75181969]]


In [8]:
model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

model.fit(x_train, y_train,
          epochs=20,
          batch_size=128)
score = model.evaluate(x_test, y_test, batch_size=128)

W0724 11:50:28.569626 16000 deprecation_wrapper.py:119] From C:\Users\sunny.DESKTOP-QGFGEEK\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0724 11:50:28.831403 16000 deprecation.py:506] From C:\Users\sunny.DESKTOP-QGFGEEK\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0724 11:50:28.932114 16000 deprecation_wrapper.py:119] From C:\Users\sunny.DESKTOP-QGFGEEK\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0724 11:50:28.957216 16000 deprecation_wrapper.py:119] From C:\Users\sunny.DESKTOP-QGFGEEK\Anacond

Epoch 1/20
1000/1000 [==============================] - 2s 2ms/step - loss: 2.4073 - acc: 0.1090
Epoch 2/20
1000/1000 [==============================] - 0s 21us/step - loss: 2.3720 - acc: 0.0960
Epoch 3/20
1000/1000 [==============================] - 0s 20us/step - loss: 2.3517 - acc: 0.1050
Epoch 4/20
1000/1000 [==============================] - 0s 19us/step - loss: 2.3256 - acc: 0.1030
Epoch 5/20
1000/1000 [==============================] - 0s 21us/step - loss: 2.3238 - acc: 0.1010
Epoch 6/20
1000/1000 [==============================] - 0s 19us/step - loss: 2.3207 - acc: 0.1210
Epoch 7/20
1000/1000 [==============================] - 0s 20us/step - loss: 2.3141 - acc: 0.1090
Epoch 8/20
1000/1000 [==============================] - 0s 21us/step - loss: 2.3089 - acc: 0.1090
Epoch 9/20
1000/1000 [==============================] - 0s 22us/step - loss: 2.3079 - acc: 0.1050
Epoch 10/20
1000/1000 [==============================] - 0s 20us/step - loss: 2.3046 - acc: 0.1160
Epoch 11/20
1000/100

In [10]:
import pandas as pd
import numpy as np

In [35]:
#read csv prepare data set
dataset_source = 'C:/Users/sunny.DESKTOP-QGFGEEK/Desktop/GitClone/1_camera_gait_analysis/matched_excel/walkR1.csv'
dataset_df = pd.read_csv(dataset_source,sep = ',',engine='python')



In [37]:
#crate numpy array of input
input_array = pd.DataFrame(dataset_df.iloc[:,:6]).to_numpy()
print(input_array)

[[0.1390625  0.54076087 0.128125   0.63858696 0.0859375  0.74456522]
 [0.1484375  0.53804348 0.1375     0.63858696 0.09375    0.73913043]
 [0.1546875  0.53804348 0.1421875  0.63586957 0.096875   0.73913043]
 [0.159375   0.53532609 0.1484375  0.63586957 0.1015625  0.73641304]
 [0.165625   0.53532609 0.1546875  0.63586957 0.10625    0.73369565]
 [0.171875   0.53532609 0.1609375  0.63586957 0.1109375  0.73369565]
 [0.184375   0.53532609 0.1734375  0.63586957 0.1234375  0.72826087]
 [0.190625   0.53532609 0.18125    0.63586957 0.128125   0.72554348]
 [0.196875   0.53532609 0.1875     0.63586957 0.1359375  0.72554348]
 [0.203125   0.53532609 0.1953125  0.63586957 0.1421875  0.72554348]
 [0.209375   0.53532609 0.203125   0.63586957 0.15       0.72282609]
 [0.221875   0.53532609 0.2171875  0.63586957 0.1640625  0.72282609]
 [0.228125   0.53532609 0.225      0.63586957 0.171875   0.72282609]
 [0.234375   0.5326087  0.2328125  0.63586957 0.178125   0.7201087 ]
 [0.240625   0.5326087  0.2390625 

In [24]:
#crate numpy array of target
target_array = pd.DataFrame(dataset_df.iloc[:,6:]).to_numpy()
print(input_array)

[[0.87067083]
 [0.85612335]
 [0.83936787]
 [0.82047685]
 [0.79954282]
 [0.77668477]
 [0.75204932]
 [0.72581093]
 [0.6981699 ]
 [0.66934798]
 [0.6395826 ]
 [0.60911732]
 [0.57818963]
 [0.54701347]
 [0.51576967]
 [0.48459327]
 [0.45357663]
 [0.42278048]
 [0.3922544 ]
 [0.36206505]
 [0.3323217 ]
 [0.30319713]
 [0.27493723]
 [0.24785868]
 [0.22233328]
 [0.19876187]
 [0.17754275]
 [0.15903873]
 [0.14354643]
 [0.13127568]
 [0.12233383]
 [0.11672042]
 [0.11432872]
 [0.11495303]
 [0.11830332]
 [0.12402638]
 [0.13173647]
 [0.14104778]
 [0.15161543]
 [0.16316493]
 [0.1755213 ]
 [0.1886167 ]
 [0.20248015]
 [0.217197  ]
 [0.23284605]
 [0.2494115 ]
 [0.26670262]
 [0.28431455]
 [0.30165882]
 [0.31804927]
 [0.33280868]
 [0.34535947]
 [0.3552918 ]
 [0.36239982]
 [0.36668408]
 [0.368332  ]
 [0.36767095]
 [0.36511115]
 [0.36108895]
 [0.3560132 ]
 [0.3502304 ]
 [0.34400817]
 [0.33753707]
 [0.33094118]
 [0.3242999 ]
 [0.31766392]
 [0.31107183]
 [0.30455832]
 [0.29815747]
 [0.29190233]
 [0.28582457]
 [0.27

In [48]:
#my code


import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Dropout
from keras import regularizers

#read data set


# define the keras model
model = Sequential()
model.add(Dense(16, input_dim=6,kernel_regularizer=regularizers.l2(0.01), activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(8, activation='relu',kernel_regularizer=regularizers.l2(0.01)))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid',kernel_regularizer=regularizers.l2(0.01)))



# compile the keras model
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])


model.fit(input_array, target_array, epochs=150, batch_size=10)

# evaluate the keras model
_, accuracy = model.evaluate(input_array,  target_array)
print('Accuracy: %.2f' % (accuracy*100))

Epoch 1/150
128/128 [==============================] - 1s 6ms/step - loss: 0.3453 - acc: 0.0000e+00
Epoch 2/150
128/128 [==============================] - 0s 164us/step - loss: 0.3146 - acc: 0.0000e+00
Epoch 3/150
128/128 [==============================] - 0s 179us/step - loss: 0.2764 - acc: 0.0000e+00
Epoch 4/150
128/128 [==============================] - 0s 164us/step - loss: 0.2426 - acc: 0.0000e+00
Epoch 5/150
128/128 [==============================] - 0s 171us/step - loss: 0.2185 - acc: 0.0000e+00
Epoch 6/150
128/128 [==============================] - 0s 179us/step - loss: 0.2046 - acc: 0.0000e+00
Epoch 7/150
128/128 [==============================] - 0s 179us/step - loss: 0.1926 - acc: 0.0000e+00
Epoch 8/150
128/128 [==============================] - 0s 171us/step - loss: 0.1808 - acc: 0.0000e+00
Epoch 9/150
128/128 [==============================] - 0s 171us/step - loss: 0.1777 - acc: 0.0000e+00
Epoch 10/150
128/128 [==============================] - 0s 164us/step - loss: 0.1663

In [49]:
# make class predictions with the model
predictions = model.predict_classes(input_array)
# summarize the first 5 cases
for i in range(5):
    print('%s => %d (expected %d)' % (input_array[i].tolist(), predictions[i], target_array[i]))

[0.1390625, 0.5407608695652174, 0.128125, 0.6385869565217391, 0.0859375, 0.7445652173913043] => 0 (expected 0)
[0.1484375, 0.5380434782608695, 0.1375, 0.6385869565217391, 0.09375, 0.7391304347826086] => 0 (expected 0)
[0.1546875, 0.5380434782608695, 0.1421875, 0.6358695652173914, 0.096875, 0.7391304347826086] => 0 (expected 0)
[0.159375, 0.5353260869565217, 0.1484375, 0.6358695652173914, 0.1015625, 0.7364130434782609] => 0 (expected 0)
[0.165625, 0.5353260869565217, 0.1546875, 0.6358695652173914, 0.10625, 0.7336956521739131] => 0 (expected 0)


In [30]:
#%%
import numpy 
import pandas as pd
# load dataset
yacht = pd.read_csv(dataset_source, names=["THIx", "THIy", "KNEx", "KNEy", "TIBx", "TIBy", "knee angle"], sep=",")
yacht.head()
#%%
yacht.isnull().values.any()

#%%
from sklearn.model_selection import train_test_split
X = yacht.drop(["knee angle"], axis=1)
y = yacht["knee angle"]
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

#%%
x_train

#%%
x_train.shape

#%%
y_train

#%%
from keras import models
from keras import layers

#%%
def build_model():
    model = models.Sequential()
    model.add(layers.Dense(64, activation='relu',
    input_shape=(x_train.shape[1],)))
    model.add(layers.Dense(64, activation='relu'))
    model.add(layers.Dense(1))
    model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
    return model

#%%
import numpy as np
k = 4
num_val_samples = len(x_train) // k
num_epochs = 100
all_scores = []
for i in range(k):
    print('processing fold #', i)
    val_data = x_train[i * num_val_samples: (i + 1) * num_val_samples]
    val_targets = y_train[i * num_val_samples: (i + 1) * num_val_samples]
    
    partial_x_train = np.concatenate(
        [x_train[:i * num_val_samples],
        x_train[(i + 1) * num_val_samples:]],axis=0
    )
    partial_y_train = np.concatenate(
        [y_train[:i * num_val_samples],
        y_train[(i + 1) * num_val_samples:]],axis=0
    )
    model = build_model()
    model.fit(partial_x_train, partial_y_train,
            epochs=num_epochs, batch_size=1, verbose=0)
    val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
    all_scores.append(val_mae)

#%%
num_epochs = 500
all_mae_histories = []
for i in range(k):
    print('processing fold #', i)
    val_data = x_train[i * num_val_samples: (i + 1) * num_val_samples]
    val_targets = y_train[i * num_val_samples: (i + 1) * num_val_samples]
    
    partial_x_train = np.concatenate(
        [x_train[:i * num_val_samples],
        x_train[(i + 1) * num_val_samples:]],axis=0
    )
    partial_y_train = np.concatenate(
        [y_train[:i * num_val_samples],
        y_train[(i + 1) * num_val_samples:]],axis=0
    )
    model = build_model()
    history = model.fit(partial_x_train, partial_y_train,
            validation_data=(val_data, val_targets),
            epochs=num_epochs, batch_size=1, verbose=0)
    mae_history = history.history['val_mean_absolute_error']
    all_mae_histories.append(mae_history)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3
processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3
